CREATE TABLE [dbo].[Reviews]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(100),
	[Message] NVARCHAR(1000) NOT NULL,
	[CreatedAt] DATETIME2(7) NOT NULL DEFAULT GETDATE(),
	[Visible] BIT NOT NULL DEFAULT 1
);
